#!/usr/bin/env python
"""
Calibrate odocmetry with data from a rosbag file
"""
from argparse import ArgumentParser

import numpy as np
import rosbag
import scipy.optimize
from ruvu_odometry_calibration.odometry_calibration import bag_to_datapoints, Parameters, loss


def main(bagfile):
    print('Loading bagfile:', bagfile)
    with rosbag.Bag(bagfile) as bag:
        data = bag_to_datapoints(bag)

    def f(x):
        parameters = Parameters(x[0], x[1])
        errs = loss(data, parameters)
        print('err:', np.linalg.norm(errs), parameters)
        return np.ndarray.flatten(errs)

    bounds = (0.5, 2)
    result = scipy.optimize.least_squares(f, [1, 1], bounds=list(zip(bounds, bounds)))
    del result['fun']
    del result['jac']
    print(result)
    print('wheel_separation_multiplier', result.x[0])
    print('wheel_radius_multiplier', result.x[1])


if __name__ == '__main__':
    parser = ArgumentParser(description=__doc__)
    parser.add_argument('bagfile', help='input bagfile')

    args = parser.parse_args()
    main(**vars(args))
